### PR TITLE
Regenerate with updated superflore

### PR DESCRIPTION
**Pull request by shr-project**

### CODE REVIEW

**Comment by herb-kuta-lge** [comment]
Please defer generating ROS_SUPERFLORE_GENERATED_BUILDTOOLS with a _<ROS_DISTRO> suffix until Milestone 12 (implement layer version 3 part 2).

**Comment by shr-project** [comment]
Why? It's already part of superflore PR and I've already verified that it actually helps with Milestone 12 as well.

**Comment by herb-kuta-lge** [comment]
Because we don't have a complete solution for building ROS 1 packages for a ROS 2 distro, and there's no sense introducing changes that might not be part of what we eventually come up with.

**Comment by shr-project** [comment]
But it builds and is more flexible, so it's much better starting point for that solution than what we have now. If we fix the order where ros-distro.inc are being included in the build, it might be enough to get it working completely - without regenerating anything and without changing superflore again.

**Comment by herb-kuta-lge** [comment]
What about all of the other variables in (generated-)ros-distro? Might they also need _<ROS_DISTRO> suffixes?

**Comment by herb-kuta-lge** [comment]
Everything should now have been cherry-picked into the herb-kuta-lge/meta-ros[master-draft-next] chain.

**Pull request closed without merging**
