### PR TITLE
Missing recipes

### PR DESCRIPTION
**Pull request by shr-project**
Missing recipes to buidl slam-karto and cartographer-ros.

Should be enough to build webos-image-ros-turtlebot3-all now.

It needs this addition to ros-distro (or local.conf), fortran is needed for lapack:

ROS_UNRESOLVED_PLATFORM_PKG_libblas-dev = "openblas"
ROS_UNRESOLVED_PLATFORM_PKG_liblapack-dev = "lapack"

```
# Recipe needs FORTRAN support (copied from conf/local.conf.sample.extended)
# Enabling FORTRAN
# Note this is not officially supported and is just illustrated here to
# show an example of how it can be done
# You'll also need your fortran recipe to depend on libgfortran
FORTRAN_forcevariable = ",fortran"
RUNTIMETARGET_append_pn-gcc-runtime = " libquadmath"
```

### CODE REVIEW

**Comment by herb-kuta-lge** [comment]
All commits added somewhere along `[master-draft]`.

**Comment by shr-project** [comment]
The last one "ceres-solver: add a fix for wrong paths pointing to wrong RSS" seems to be missing in master-draft as well as thud-draft-tb3 branches

**Comment by herb-kuta-lge** [comment]
Forgot to (force) push `[master-draft]`; it's there now.

**Comment by shr-project** [comment]
Only [master-draft-next] branch was updated, still missing in [master-draft].

**Comment by shr-project** [comment]
And it's also needed in [thud-draft-tb3], isn't it? other ceres-solver changes are there now.

**Comment by herb-kuta-lge** [comment]
Fixed.

**Pull request closed without merging**
