### PR TITLE
pcl: Fix build error

### PR DESCRIPTION
**Pull request by eigendude**
While trying to build against Yocto Zeus, I received the following error:

```
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   HAVE_POSIX_MEMALIGN_EXITCODE (advanced)
   HAVE_POSIX_MEMALIGN_EXITCODE__TRYRUN_OUTPUT (advanced)
```

By adding `HAVE_POSIX_MEMALIGN_EXITCODE__TRYRUN_OUTPUT` to the cmake defines, the error goes away and compilation succeeds.

### CODE REVIEW

**Comment by eigendude** [comment]
Is there somewhere I can report the compiler error?

**Comment by herb-kuta-lge** [comment]
> Is there somewhere I can report the compiler error?

**Comment by herb-kuta-lge** [comment]
> Is there somewhere I can report the compiler error?

There is now. Please rebase your pull request to the `[zeus-draft]` branch of this repo and it will eventually make its way into `ros/meta-ros`. Thanks for your contribution!

**Comment by eigendude** [comment]
@herb-kuta-lge rebased

**Comment by herb-kuta-lge** [comment]
@eigendude Please fix the conflict. Also, it still says at the top that the pull request is for `[master-draft]`; it should be for `[zeus-draft]`.

**Comment by eigendude** [comment]
@herb-kuta-lge OK, for reals this time

**Pull request merged**
