### PR TITLE
mcf files

### PR DESCRIPTION
**Pull request by shr-project**

### CODE REVIEW

**Review by herb-kuta-lge — CHANGES_REQUESTED** [review]
This is already in [build-draft-ms9a].

**Review by herb-kuta-lge — CHANGES_REQUESTED** [review]
This is already in [build-draft-ms9b].

**Review by herb-kuta-lge — CHANGES_REQUESTED** [review]
Please drop the # prefix to 91: GitHub thinks it's a reference to met-ros/pull/91.

**Review by herb-kuta-lge — CHANGES_REQUESTED** [review]
Please drop the # prefix to 93: GitHub thinks it's a reference to met-ros/pull/93.

Ubuntu bionic has Qt 5.9, so we should migrate to build 92 instead of this one. (We'll start using the versions of platform packages provided by OE for **warrioir**.)

**Review by herb-kuta-lge — CHANGES_REQUESTED** [review]
Please split the *-warrior.mcf files into a separate commit and move to [build-draft-ms11]. Move the addition of *-zeus.mcf and *-dunfell.mcf into [build-draft-next].

**Review by herb-kuta-lge — CHANGES_REQUESTED** [review]
Please drop the # prefix to 138: GitHub thinks it's a reference to met-ros/pull/138.

**Comment by shr-project** [comment]
> Please split the *-warrior.mcf files into a separate commit and move to [build-draft-ms11]. Move the addition of *-zeus.mcf and *-dunfell.mcf into [build-draft-next].

What's wrong with the zeus and dunfell files? They are in development folder like warrior is and they do build at least something.

**Comment by shr-project** [comment]
> Please drop the # prefix to 93: GitHub thinks it's a reference to met-ros/pull/93.
> 
> Ubuntu bionic has Qt 5.9, so we should migrate to build 92 instead of this one. (We'll start using the versions of platform packages provided by OE for **warrioir**.)

Qt 5.9 wasn't well tested in webOS, and we'll need to upgrade to 5.12 soon to use even newer OSE, so I think we should go directly to 5.12 from 93.

**Comment by herb-kuta-lge** [comment]
> Qt 5.9 wasn't well tested in webOS, 

If that's the case, then I think we should stay with build 91 (Qt v5.6) until we're ready to migrate to webOS OSE 2.x . Also, by keeping Qt at v5.6, we don't have to update [REP-2000](https://www.ros.org/reps/rep-2000.html).

**Comment by herb-kuta-lge** [comment]
> What's wrong with the zeus and dunfell files? They are in development folder like warrior is and they do build at least something.

Nothing, I guess, but please put them in a separate commit from the warrior files because these two OE releases do not yet appear on our roadmap.

Would "files-contrib" be a better name for the folder with them than "files/development"?

**Comment by shr-project** [comment]
> > Qt 5.9 wasn't well tested in webOS,
> 
> If that's the case, then I think we should stay with build 91 (Qt v5.6) until we're ready to migrate to webOS OSE 2.x . Also, by keeping Qt at v5.6, we don't have to update [REP-2000](https://www.ros.org/reps/rep-2000.html).

The advantage of build 93 is that it has Qt v5.12 which is well tested in webOS and doesn't need any other changes in meta-ros to make it compatible. So we could update rep-2000 independently of the bigger upgrade to OSE 2.1 when we'll need to modify meta-ros-webos as well.

**Comment by herb-kuta-lge** [comment]
> The advantage of build 93 is that it has Qt v5.12 which is well tested in webOS

**Comment by herb-kuta-lge** [comment]
> The advantage of build 93 is that it has Qt v5.12 which is well tested in webOS

But so is v5.6, right? Why not change as little as possible to support **eolquent**?

**Comment by herb-kuta-lge** [comment]
The eloquent ones have been cherry-picked into the herb-kuta-lge/meta-ros[build-draft-next] chain.

**Comment by shr-project** [comment]
Replaced with https://github.com/herb-kuta-lge/meta-ros/pull/35

**Pull request closed without merging**
