### PR TITLE
Master draft

### PR DESCRIPTION
**Pull request by shr-project**

### CODE REVIEW

**Comment by shr-project** [comment]
What's the status of this PR? Seems like some changes were integrated and some weren't. Also e.g. those kernel backports from https://github.com/herb-kuta-lge/meta-ros/pull/26/commits are also missing in current master-draft branch.

**Comment by herb-kuta-lge** [comment]
> What's the status of this PR? Seems like some changes were integrated and some weren't.

Which changes are missing?

> those kernel backports from https://github.com/herb-kuta-lge/meta-ros/pull/26/commits are also missing in current master-draft branch.

Aren't the first two the ones that left media broken on the RPi 3 B+ that we decided not to use? I dropped the third because in the short-term we aren't worrying about raspberrypi3-64 and in the long-term, webOS OSE won't support either form of it.

**Comment by shr-project** [comment]
> Which changes are missing?

e.g. this one is still needed when melodic is regenerated with superflore

`
commit bde77009965bf4b9445dff8f56c3a46e1df1f0d0
Author: Herb Kuta <herb.kuta@lge.com>
Date:   Mon Sep 9 16:52:09 2019 -0700

    TEMP melodic/ros-distro.inc: Add ROS_UNRESOLVED_PLATFORM_PKG_* settings for new recipes
`

but missing in latest master-draft, causing those build issues I've mentioned on Friday.

**Comment by shr-project** [comment]
commit e3c1bf16579277b9ce28ba9adc11ce7de1922955
Author: Martin Jansa <martin.jansa@lge.com>
Date:   Sat Sep 7 09:35:52 2019 -0700

    sparse-bundle-adjustment: fix dependencies

    * add dependency on suitesparse-cholmod and suitesparse-cxsparse instead of just suitesparse
    * we have separate recipes for each suitesparse project

is also missing, somehow incorrectly squashed with
commit 35c8ae0d53a4174e5d833da0a5845354b82f73bc
Author: Martin Jansa <martin.jansa@lge.com>
Date:   Fri Sep 13 02:32:53 2019 -0700

    sparse-bundle-adjustment: drop ROS_UNRESOLVED_PLATFORM_PKG_libblas-dev

to create:
commit ab4ed425d0f57699fe5c2d3974da5c18020cd6f5
Author: Martin Jansa <martin.jansa@lge.com>
Date:   Sat Sep 7 09:35:52 2019 -0700

    {melodic} sparse-bundle-adjustment: fix dependencies

in the rebased master-draft

**Comment by shr-project** [comment]
I've created https://github.com/herb-kuta-lge/meta-ros/pull/30 to re-add missing changes.

**Pull request closed without merging**
